Update Query API to accept wrapper classes as filters
specs-feup/lara-framework pull request #63
Opened 2024-05-29 15:05 UTC by lm-sousa

Both `Query` and `Selector` APIs now accept wrapper classes as filters instead of strings.
Method variants that use strings to filter by joinpoint type have been tagged as deprecated and will be removed in the future.
Both APIs now report correct type information about their results.

2024-06-22 18:42 UTC, joaobispo commented
If someone wants to do a Query in a programmatic way, where a functions accepts an array of join point types, this API will work, as it would currently with the strings?

2024-06-25 15:57 UTC, lm-sousa commented
Short answer? Yes.
Searching with the old string API is still supported (but tagged as deprecated and for removal).

In that context, using the new API would be a matter of modifying that function to receive an array of Joinpoint constructors instead of strings. Then, on each iteration of a loop, a constructor would be used.
Type inference (and supported filtering) will be limited to things only supported by the base class of the array (in the worst case, only the base Joinpoint). What I mean by this is that, a type error will be thrown if you try to filter by the content of a attribute not shared by all joinpoint types defined in the function arguments.

2024-07-03 12:32 UTC, joaobispo requested changes

2024-07-03 12:32 UTC, joaobispo commented on Lara-JS/src-api/weaver/JoinPoints.ts
> -    jpType?: string
The idea of passing the function instead of a list was to allow, in the future, for the function to return an iterable, instead of forcing the creating of a list with all jps before the filtering.

Add a comment with this information, that for streaming to be implemented, we will need to change the input list to be for instance, an iterable/generator.

Right now, we should be very close for search() to work in a stream-like way, on the Java-side the base methods already return Streams.

2024-07-03 12:32 UTC, joaobispo commented on Lara-JS/src-api/weaver/Query.ts
> +   * @deprecated Use the new version of this function that receives a class as the first parameter.
Not sure yet if the string methods should be deprecated, although it should be discouraged. Is there any other method of signaling that this version is not the preferred one?

2024-07-03 16:01 UTC, lm-sousa commented on Lara-JS/src-api/weaver/Query.ts
> +   * @deprecated Use the new version of this function that receives a class as the first parameter.
Not really. The deprecation tag is [the only one available](https://tsdoc.org/pages/tags/deprecated/). 
However, the meaning of the word "deprecated", is appropriate here and falls within your intention. 

> to withdraw official support for or discourage the use of (something, such as a software product) in favor of a newer or better alternative

To deprecate does not mean to tag for removal (even though that is my _long-term_ idea).

2024-07-03 16:02 UTC, lm-sousa commented on Lara-JS/src-api/weaver/JoinPoints.ts
> -    jpType?: string
I'll open an issue for this comment. That way it still gets documented without polluting the code base.

2024-07-08 14:18 UTC, merged